sources:
  nginx_logs:
    type: "file"
    include:
      - "/var/log/nginx/access.log"
    read_from: "end"

transforms:
  parse:
    type: "remap"
    inputs:
      - "nginx_logs"
    source: |
      . = parse_nginx_log!(.message, format: "combined")

sinks:
  send_remote:
    type: vector
    inputs:
      - parse
    address: "1.2.3.4:6000"  # replace with the actual IP/domain
    # Optionally enable back-pressure ack:
    acknowledgements:
      enabled: true
