sources:
  nginx_logs:
    type: "file"
    include:
      - "/var/log/nginx/access.log"
    read_from: "end"

transforms:
  parse:
    type: "remap"
    inputs:
      - "nginx_logs"
    source: |
      . = parse_nginx_log!(.message, format: "combined")

sinks:
 console:
   type: "console"
   inputs:
     - "parse"
   encoding:
     codec: "json"
